# Generated by Django 6.0.1 on 2026-01-14 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=500, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('imagem_perfil', models.CharField(blank=True, max_length=500, null=True)),
                ('imagem_fundo', models.CharField(blank=True, max_length=500, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField()),
                ('preco_ingresso', models.IntegerField()),
                ('total_ingressos', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.empresa')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_pagamento', models.CharField(db_index=True, max_length=50, unique=True)),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.FloatField()),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão')], max_length=10)),
                ('nome_comprador', models.CharField(max_length=255)),
                ('email_comprador', models.EmailField(max_length=254)),
                ('cpf_comprador', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='api.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='api.evento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_hash', models.CharField(db_index=True, max_length=11, unique=True)),
                ('comprado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantidade', models.IntegerField(default=1)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('pix', 'PIX'), ('cartao', 'Cartão')], max_length=10, null=True)),
                ('nome_comprador', models.CharField(blank=True, max_length=255, null=True)),
                ('email_comprador', models.EmailField(blank=True, max_length=254, null=True)),
                ('cpf_comprador', models.CharField(blank=True, max_length=14, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='api.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='api.evento')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='api.pagamento')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
                'db_table': 'ingressos',
                'ordering': ['-comprado_em'],
            },
        ),
    ]
