# Generated by Django 6.0.1 on 2026-01-22 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 20, 46, 56, 962783, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
